/**
 * The MIT License
 * Copyright © 2018 Nordic Institute for Interoperability Solutions (NIIS)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.09 at 08:02:13 PM EEST 
//


package eu.x_road.emta_v6;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.x_road.emta_v6 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.x_road.emta_v6
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XteeFieAndmedResponseType }
     * 
     */
    public XteeFieAndmedResponseType createXteeFieAndmedResponseType() {
        return new XteeFieAndmedResponseType();
    }

    /**
     * Create an instance of {@link XteeFieAndmed }
     * 
     */
    public XteeFieAndmed createXteeFieAndmed() {
        return new XteeFieAndmed();
    }

    /**
     * Create an instance of {@link PersonalIdentityCode }
     * 
     */
    public PersonalIdentityCode createPersonalIdentityCode() {
        return new PersonalIdentityCode();
    }

    /**
     * Create an instance of {@link XteeFieAndmedResponse }
     * 
     */
    public XteeFieAndmedResponse createXteeFieAndmedResponse() {
        return new XteeFieAndmedResponse();
    }

    /**
     * Create an instance of {@link SelfEmployedPerson }
     * 
     */
    public SelfEmployedPerson createSelfEmployedPerson() {
        return new SelfEmployedPerson();
    }

    /**
     * Create an instance of {@link XteeFieAndmedResponseType.FieJada }
     * 
     */
    public XteeFieAndmedResponseType.FieJada createXteeFieAndmedResponseTypeFieJada() {
        return new XteeFieAndmedResponseType.FieJada();
    }

}
